<footer>
    <div class="row">
        <div class="col span-1-of-2">
            <ul class="footer-nav">
                <li><a href="#home">Početna</a></li>
                <li><a href="#service">Usluge</a></li>
                <li><a href="#about">O nama</a></li>
                <li><a href="#contact">Kontakt</a></li>
            </ul>
        </div>
        <div class="col span-1-of-2">
            <ul class="social-links">
                <li>
                    <a href="https://www.facebook.com/imporium.org">
                        <i class="ion-social-facebook hvr-grow"></i>
                    </a>
                </li>
            </ul>
        </div>
    </div>
    <div class="row">
            <p>
                <span class="animated flipInX">&copy;Imporium</span>
            </p>
    </div>
</footer>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
<script src="//cdn.jsdelivr.net/respond/1.4.2/respond.min.js"></script>
<script src="//cdn.jsdelivr.net/html5shiv/3.7.2/html5shiv.min.js"></script>
<script src="//cdn.jsdelivr.net/selectivizr/1.0.3b/selectivizr.min.js"></script>
<script src="vendors/js/jquery.waypoints.min.js"></script>
<script src="resources/js/script.js"></script>

</body>

</html>