<header id="home">
    <nav>
        <div class="row">
            <img src="pub/resources/img/logo_transparent.png" alt="ImporiuM logo" class="logo hvr-grow">
            <a href="#home"><img src="resources/img/logo.png" alt="ImporiuM logo" class="logo-black hvr-grow"></a>
            <ul class="main-nav js--main-nav">
                <li><a  href="#service">Usluge</a></li>
                <!--<li><a href="#works">TEST</a></li>-->
                <li><a href="#about">O nama</a></li>
                <li><a href="#contact">Kontakt</a></li>
            </ul>
            <a class="mobile-nav-icon js--nav-icon"><i class="ion-navicon-round"></i></a>
        </div>
    </nav>
    <div class="hero-text-box">
        <h1>ImporiuM</h1>
        <a class="btn btn-full js--scroll-to-start" href="#">Saznaj više</a>
    </div>

</header>