<!DOCTYPE html>
<html lang="en">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="pub/vendors/css/normalize.css">
    <link rel="stylesheet" type="text/css" href="pub/vendors/css/grid.css">
    <link rel="stylesheet" type="text/css" href="pub/vendors/css/ionicons.min.css">
    <link rel="stylesheet" type="text/css" href="pub/vendors/css/animate.css">
    <link rel="stylesheet" type="text/css" href="pub/vendors/css/hover-min.css">
    <link rel="stylesheet" type="text/css" href="pub/resources/css/style.css">
    <link rel="stylesheet" type="text/css" href="pub/resources/css/queries.css">
    <link rel="icon" href="pub/resources/img/logo_icon.png">
    <script src="https://kit.fontawesome.com/cac0b65e9b.js" crossorigin="anonymous"></script>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500;700&display=swap" rel="stylesheet">
    <title><?= SITENAME ?></title>
</head>
<body>
<?php include 'header.phtml';?>