<?php
    include 'includes/meta.phtml';
    include 'includes/header.phtml';
?>
        <section class="section-service js--section-features" id="service">
            <div class="row">
                <h2>Usluge</h2>
                <p class="long-copy">
                   Obratite nam se sa povjerenjem!
                </p>
            </div>
            <br><br>
            <!--
            <div class="row js--wp-1">
            -->
            <div class="row">
                <div class="col span-2-of-8 box">
                    <i class="fab fa-windows icon-big hvr-grow"></i>
                    <h3>Instalacija Windows OS</h3>
                    <p>
                       Instalacija operativnog sustava Windows
                    </p>
                </div>
                <div class="col span-2-of-8 box">
                    <i <i class="fas fa-laptop-code  icon-big hvr-grow"></i>
                    <h3>Izrada web stranica</h3>
                    <p>
                        Možete biti kreativni i reći nam svoje želje ili se prepustiti našim idejama pri izradi Vaše stranice
                    </p>
                </div>
                <div class="col span-2-of-8 box">
                    <i class="fas fa-server icon-big hvr-grow"></i>
                    <h3>Hosting web stranica</h3>
                    <p>
                        Za sve Vaše stranice dostupan je naš hosting
                    </p>
                </div>
                <div class="col span-2-of-8 box">
                    <i class="fas fa-tools icon-big hvr-grow"></i>
                    <h3>Održavanje računala</h3>
                    <p>
                        Ostale djelatnosti u vezi s informacijskom tehnologijom i računalima
                    </p>
                </div>
            </div>   
        </section>

        <section class="section-portfolio">
            <ul class="portfolio-showcase clearfix">
                <li>
                    <figure class="portfolio-photo">
                        <img src="resources/img/1.jpg" alt="">
                    </figure>
                </li>
                <li>
                    <figure class="portfolio-photo">
                        <img src="resources/img/2.jpg" alt="">
                    </figure>
                </li>
                <li>
                    <figure class="portfolio-photo">
                        <img src="resources/img/3.jpg" alt="">
                    </figure>
                </li>
                <li>
                    <figure class="portfolio-photo">
                        <img src="resources/img/4.jpg" alt="">
                    </figure>
                </li>
            </ul>
            <ul class="portfolio-showcase clearfix">
                <li>
                    <figure class="portfolio-photo">
                        <img src="resources/img/5.jpg" alt="">
                    </figure>
                </li>
                <li>
                    <figure class="portfolio-photo">
                        <img src="resources/img/6.jpg" alt="">
                    </figure>
                </li>
                <li>
                    <figure class="portfolio-photo">
                        <img src="resources/img/7.jpg" alt="">
                    </figure>
                </li>
                <li>
                    <figure class="portfolio-photo">
                        <img src="resources/img/8.jpg" alt="">
                    </figure>
                </li>
            </ul>
        </section>


        <section class="section-about" id="about">
            <div class="row">
                <h2>O nama</h2>
            </div>

            <!--
            <div class="row js--wp-3">
            -->
            <div class="row">
                <div class="col span-12-of-12 box">
                    Iz ljubavi prema dizajniranju, programiranju i video-igricama stvoren je ImporiuM. Mala tvrtka iz malog grada s velikom željom i entuzijazmom za rad i napredak, koja ide uz korak s računalnom tehnologijom.
                    ImporiuM je prvenstveno nastao kako bi pomogao korisniku na daljinu kada i gdje je to potrebno.
                </div>
            </div>
            
        </section>

        <section class="section-contact js--section-contact" id="contact">
            <div class="row">
                <h2>Kontakt</h2>
            </div>
            <div class="row">
                <div class="col span-12-of-12">
                    <div class="contact-box js--wp-4">
                        <div>
                            <ul>
                                <li> Slavonska 27, 33520 Slatina</li>
                                <li> imporium.org@gmail.com </li>
                                <li> 033/ 550-666 </li>
                                <li><a href="https://www.facebook.com/imporium.org" class="link-decoration">@imporium.org</a></li>
                            </ul>
                        </div>
                        <div>
                            <iframe class="contact-frame" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2786.3333779214468!2d17.671741416200735!3d45.70434842540683!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47678a5ab471a565%3A0x17f54d980cac43ce!2sSlavonska%20ul.%2027%2C%2033520%2C%20Slatina!5e0!3m2!1sen!2shr!4v1614764442171!5m2!1sen!2shr"
                                    allowfullscreen="" loading="lazy"></iframe>
                        </div>
                    </div>
                </div>
            </div>
        </section>

        
<?php
    include 'includes/footer.phtml';
?>